"""create context embeddings table

Revision ID: 2a1c1b7d668d
Revises: 733f03fc2598
Create Date: 2026-09-29 10:59:32.518930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1c1b7d668d'
down_revision: Union[str, Sequence[str], None] = '733f03fc2598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_embeddings_repository_path'), 'context_embeddings', ['repository_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_embeddings_repository_path'), table_name='context_embeddings')
    op.drop_table('context_embeddings')
    # ### end Alembic commands ###
