"""create testing persistence tables

Revision ID: 7c6644be5d28
Revises: 2a1c1b7d668d
Create Date: 2026-09-30 22:29:14.980028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6644be5d28'
down_revision: Union[str, Sequence[str], None] = '2a1c1b7d668d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('test_generation_validity', sa.Float(), nullable=False),
    sa.Column('coverage_improvement', sa.Float(), nullable=False),
    sa.Column('defect_detection_rate', sa.Float(), nullable=False),
    sa.Column('development_time_reduction', sa.Float(), nullable=False),
    sa.Column('maintenance_reduction', sa.Float(), nullable=False),
    sa.Column('self_healing_success_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=False),
    sa.Column('repair_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_healing_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_executions')
    op.drop_table('self_healing_runs')
    op.drop_table('failure_analyses')
    op.drop_table('analytics_records')
    # ### end Alembic commands ###
